### ISSUE TITLE
VTTREF0 and VTTREF not connected

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-numato-opsis-hardware#12]
This is caused because we ended up with two nets, VTTREF0 and VVTREF, hence the check in the PCB didn't show they where connected.

![hdmi2usb_ddrvref_error](https://cloud.githubusercontent.com/assets/21212/8766058/564fb568-2e6d-11e5-879d-d26f44591f3d.jpg)

Ported from http://redmine.numato.in/issues/1960

**Comment by mithro** [comment]
This has been fixed in the schematic. Needs to also be fixed in the PCB.

**Comment by numato-anoopjose** [comment]
Kindly check the latest files

**Comment by mithro** [comment]
LGTM.
