### ISSUE TITLE
Add an ATX compatible power supply header

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-numato-opsis-hardware#14]
Options are;
- 24-pin ATX12V 2.x power supply connector
- 4-pin "Molex connector" — transferred directly from AT standard: +5 V and +12 V for P-ATA hard disks, CD-ROMs, 5.25 inch floppy drives and other peripherals.
- PCI-Express 12V adapter.

https://en.wikipedia.org/wiki/ATX

Ported from http://redmine.numato.in/issues/1979

**Comment by numato-anoopjose** [comment]
Updated the files

**Comment by mithro** [comment]
It appears we went with a PCI-Express 12V connector?

Is there space to add a 4-pin Molex too?

**Comment by mithro** [comment]
Poke?

**Comment by numato-anoopjose** [comment]
@mithro All the latest SMPS power supply comes with PCI express connector. I do not think the 4 pin Molex connector is necessary.

**Comment by mithro** [comment]
Okay

**Comment by mithro** [comment]
Closing based on @anoopnumato's comments.
