### ISSUE TITLE
Issues with low speed signal lines HDMI signal

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-numato-opsis-hardware#16]
The HDMI RX ports have a 15k resistor pulling them down and a 1k resistor pulling them up!?

**Comment by mithro** [comment]
From Anoop,

> The changes made on the hardware is 
> R151,R204(15K) removed, R141,R142,R197,R196 vale 
> changed from 1.5K to 49K.

**Comment by mithro** [comment]
I have applied @anoopnumato 's changes to the schematic. They still need to be applied to the PCB.

**Comment by mithro** [comment]
@anoopnumato - Please confirm these changes have been made?

**Comment by mithro** [comment]
@anoopnumato - Poke?

**Comment by mithro** [comment]
@anoopnumato There still seem to be 1.5k resistors on the HDMI Outputs. Do these need changing too?

**Comment by numato-anoopjose** [comment]
Only changes in HDMI IN
