### ISSUE TITLE
Add mounting holes for expansion boards when using a right-angle riser.

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-numato-opsis-hardware#18]
All expansion boards should follow the PCI-Express mechanical standard so they can be mounted in ITX style cases using standard risers. 

However when not using a case, it would be good to allow the expansion boards to be securely attached to the motherboard. This can be done with a standard right angle connector (such as http://www.amazon.com/gp/product/B00KZIAHW8) and some extra mounting holes in the motherboard.

**Comment by mithro** [comment]
See the following two pictures
- https://drive.google.com/file/d/0B5VlNZ_Rvdw6WVNSQkxoLVhRam8/view?usp=sharing
- https://drive.google.com/file/d/0B5VlNZ_Rvdw6TWxhWnBKeF9sU0k/view?usp=sharing

**Comment by numato-anoopjose** [comment]
@mithro It will be difficult to add , required much re-routing .

**Comment by mithro** [comment]
@anoopnumato Please provide mechanical diagrams showing the issues. There is plenty of empty space on the Opsis were we can put standoff holes.

We control the TOFE specification, so we can put the standoff holes anywhere.

**Comment by mithro** [comment]
@anoopnumato Why did you assign this back to me? Did you see my last comment?

**Comment by mithro** [comment]
@anoopnumato is going to;
- upload a couple of mechanical diagrams.
- make sure their are suitable mounting holes for half-height cards.
- (maybe) add the following (optional) mounting holes

![image](https://cloud.githubusercontent.com/assets/21212/10882162/a25619be-81bc-11e5-84e5-5027c3ab4cc6.png)
