### ISSUE TITLE
What is R99 and why is it unpopulated / unknown.

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-numato-opsis-hardware#20]
It seems to be connected to Pin 22 (RF) of the TPS53319 power supply.

**Comment by numato-anoopjose** [comment]
RF resister is used for selecting switching frequency of TPS53319,  If we left open this pin, the switching frequency will be 500Khz.

**Comment by mithro** [comment]
Can we get that marked in the schematic as such?

**Comment by numato-anoopjose** [comment]
Ok. We can add.

**Comment by mithro** [comment]
LGTM.
