### ISSUE TITLE
Feature: VGA-in

### ISSUE THREAD

**Issue by tillsteinbach** [timvideos/HDMI2USB-numato-opsis-hardware#24]
This is probably more a feature request for a future version:
Lots of speakers still expect a VGA display. So it would be great to still have one (additional) VGA input.

**Comment by mithro** [comment]
@tillsteinbach We already have an expansion board for the Digilent Atlys board (our old prototyping board) that does VGA. You can see it at https://github.com/timvideos/HDMI2USB-vmodvga

This board was made by @rohit91 as part of Google Summer of Code. You can see his work at http://dreamsxtrinsic.blogspot.de/2014/08/gsoc-project-report-vga-capture.html

It would be pretty simple to port this board to the PCI-Express interface used by the Numato Opsis board but I don't think @rohit91 has any time to do that.

**Comment by tillsteinbach** [comment]
Ahh! Nice, thanks for letting me know!

**Comment by sealne** [comment]
I plan to work on converting the layout to TOFE while Rohit plans to focus on getting it to work with the new misoc based firmware

**Comment by mithro** [comment]
@sealne and @rohit91 are working on this! Yay!

**Comment by mithro** [comment]
https://github.com/timvideos/HDMI2USB-misoc-firmware/issues/30

**Comment by mithro** [comment]
FYI There is now a TOFE template available for KiCad at https://github.com/timvideos/HDMI2USB-TOFE-kicad-template

**Comment by mithro** [comment]
I'm closing this issue as the project has it's own repo now.
