### ISSUE TITLE
DisplayPort lanes on the sink are incorrect

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-numato-opsis-hardware#25]
Compare ![DisplayCable](https://bitguru.files.wordpress.com/2008/11/displayport_pinout11a.gif) to 
![screenshot from 2015-08-25 20 18 08](https://cloud.githubusercontent.com/assets/21212/9482855/bb114410-4b66-11e5-8335-fc38b94669e9.png)

**Comment by mithro** [comment]
Potential fix? - http://www.xilinx.com/support/documentation/application_notes/xapp491.pdf

**Comment by enjoy-digital** [comment]
http://www.xilinx.com/support/documentation/user_guides/ug386.pdf

"If the TXP/TXN differential traces are swapped on a board, tie TXPOLARITY High"
and
"If the polarity of RXP/RXN needs to be inverted, RXPOLARITY must be tied High"

So it should be OK.

**Comment by mithro** [comment]
FYI - @anoopnumato @numato

**Comment by mithro** [comment]
@anoopnumato has fixed this.

![image](https://cloud.githubusercontent.com/assets/21212/10882091/082bc7bc-81bc-11e5-860b-0af5c38c6820.png)

**Comment by mithro** [comment]
With a standard DisplayPort cable;

GTPA1_DUAL_X0Y0_0(TX) goes to GTPA1_DUAL_X1Y0_1(RX)
GTPA1_DUAL_X0Y0_1(TX) goes to GTPA1_DUAL_X1Y0_0(RX)
GTPA1_DUAL_X1Y0_0(TX) goes to GTPA1_DUAL_X0Y0_1(RX)
GTPA1_DUAL_X1Y0_1(TX) goes to GTPA1_DUAL_X0Y0_0(RX)
