### ISSUE TITLE
Mini-ITX case alignment issue for I/O shield

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-numato-opsis-hardware#31]
The board has an alignment issue when amounted in an Mini-ITX case the I/O ports don't correctly line up with the I/O shield area.

**Comment by mithro** [comment]
![hdmi_box_1](https://cloud.githubusercontent.com/assets/21212/10210781/d084850c-682e-11e5-8926-ea8ee4bff141.jpg)
![img_20150822_120558](https://cloud.githubusercontent.com/assets/21212/10210826/3a79baea-682f-11e5-9935-cf1832d007cc.jpg)
![img_20150822_120606](https://cloud.githubusercontent.com/assets/21212/10210843/67ba099c-682f-11e5-83fb-ffa07d156893.jpg)

**Comment by mithro** [comment]
It appears we have some type of alignment issue with our board. The DisplayPort connector on the far right is too close to the edge and there seems to be some type of gap on the left side. I see the same issue with the board in the case I got.

@anoopnumato , can you please verify the board is matching the MiniITX / ATX standard for the hole and connector positions? It kind of looks like the board should be shifted 5mm to the right?

**Comment by numato-anoopjose** [comment]
@mithro As per the Mini-iTX spec. required spacing of the IO connector side is 7.52mm(page 9), in the attached image of Numato Opsis it was 7.32 mm.
![mini_itx](https://cloud.githubusercontent.com/assets/13266596/10214535/d7554990-6836-11e5-8cf3-59d946acac68.png)
http://www.formfactors.org/developer%5Cspecs%5CMini_ITX_Spec_V2_0.pdf

**Comment by anoopnumato** [comment]
@mithro Seems it requires 7.52 and we have 7.32!

**Comment by mithro** [comment]
What are your suggestions for fixing?

**Comment by numato-anoopjose** [comment]
@mithro Option one is change the display port TX and RX connectors clearance 3 mm instead of 5 mm.

**Comment by mithro** [comment]
My recommendation is that we do the following;
- Move P17 around the corner so it is between the USB connector and the Cypress FX2
- Move DisplayPort TX left a bit.
- Move DisplayPort RX closer to DisplayPort TX.

Is that doable?

Why is there a gap on between the side of the board and the left most edge of the board? Can you please recheck all the following too:
- The hole positioning
- The expansion header positioning

**Comment by mithro** [comment]
Distance was changed to ~13mm between connector edge and hole center.
