### ISSUE TITLE
Add a header to the SD card pins

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-numato-opsis-hardware#35]
We don't have any location for interfacing at 3V3 level. Both @enjoy-digital and @hamsternz found that the MicroSD connector was useful for that.

We should add a header to make that easy. It will also allow people to probe the signals to the SD card when playing with that feature.

**Comment by mithro** [comment]
Can you please update the schematic to look like the following 
![image](https://cloud.githubusercontent.com/assets/21212/10627525/6cb71d22-7806-11e5-8aff-afbb04e147e6.png)

Please also add a VCC3V3 and GND pins to the header.

**Comment by numato-anoopjose** [comment]
Solved
