### ISSUE TITLE
how to purchase?

### ISSUE THREAD

**Issue by CarlFK** [timvideos/HDMI2USB-numato-opsis-hardware#51]
https://hdmi2usb.tv/numato-opsis/  "Purchase a board from CrowdSupply or directly from Numato.com."

 I don't see how to purchase in either place 

`Numato Opsis  No longer available`

**Comment by mithro** [comment]
Here is a message from Numato Labs.

> On 3 May 2016 at 03:07, Numato Sales sales@numato.com wrote:
> 

---snip---

> > All boards built as part of the first batch is completely sold out. We are working on getting another batch going right now. We are expecting them to be available at CrowdSupply and on our website in 2-4 weeks from now.
> > 
> > Thanks,
> > Tom
> > Numato Lab
