### ISSUE TITLE
DP/HDMI(input)--> FPGA (Scaling)--> DP(output)

### ISSUE THREAD

**Issue by Aregaard** [timvideos/HDMI2USB-numato-opsis-hardware#62]
Hi,
I have started a project where I want to create a scaling function on the FPGA. The FPGa should accept input from DP and HDMI and send out DP.
Ex: Old application uses 480p. It is send to FPGA for upscaling to 1080p.

The main task is the following setup.
![overview](https://user-images.githubusercontent.com/16863326/35766405-4d69b1b8-08d8-11e8-8caf-d31c927ec42d.png)

Will the Numato Opsis: FPGA-based open video platform ( https://numato.com/product/numato-opsis-fpga-based-open-video-platform) fix the hardware setup for me. Or is it a bad option to use this board for scaling? 
I know it is a pretty large question, but maybe you can give me some hints.

I have been googling around I have some options but none give the same possibilities as Numato Opsis video platform.
Nexys Video Platform (Artix-7) It only has HDMI-->FPGA-->mini-DP. 490$

**Comment by mithro** [comment]
Sounds like a cool project! The Numato Opsis should be a decent fit your for your idea. (Do be warned that this project will require a reasonable amount of work and is definitely non-trivial and will require more work than doing the same thing in software.)

We would love to have this upscaling feature as part of the [HDMI2USB-litex-firmware too](https://github.com/mithro/HDMI2USB-litex-firmware)! FYI The Opsis board was originally designed for the [hdmi2usb.tv](https://hdmi2usb.tv) project. We had a [Google Summer of Code student](https://summerofcode.withgoogle.com/) work on creating the low level primitives to do colorspace-correct scaling operations. You can see his work here -> https://github.com/timvideos/HDMI2USB-litex-firmware/pull/270 and https://github.com/enjoy-digital/litevideo/tree/master/litevideo/float_arithmetic that might also be useful to you.

Feel free to join us on the [#timvideos](http://webchat.freenode.net/?channels=%23timvideos&uio=d4) and hang out. We are a friendly bunch!

Hope this helps!

<blockquote><img src="https://avatars1.githubusercontent.com/u/1450143?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/enjoy-digital/litevideo">enjoy-digital/litevideo</a></strong></div><div>litevideo - Small footprint and configurable video cores</div></blockquote>
